build:

  unit_tests:
    image: python:2-alpine
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
    commands:
      - mkdir -p cache
      - pip install -r requirements-dev.txt --cache-dir=cache
      - pip install coveralls --cache-dir=cache
      - python setup.py develop
      - nosetests -s -v tests

  pypy_unit_tests:
    # just enough variation to make a matrix not viable
    image: pypy:2
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
    commands:
      - mkdir -p cache
      - pip install -r requirements-dev.txt --cache-dir=cache
      - pip install coveralls --cache-dir=cache
      - pypy setup.py develop
      - nosetests -s -v tests
    when:
      event: push
      branch: master


  documentation:
     image: python:2-alpine
     commands:
       - apk update
       - apk add git make
       - git config --global user.email "cibot@cloud-custodian.io"
       - git config --global user.name "Custodian CI"
       - pip install -r requirements-dev.txt --cache-dir=cache
       - make sphinx
       - git remote update origin --prune
       - make ghpages
     when:
       event: push
       branch: master

deploy:
  # sphinx documentation build / per documentation build section
  git_push:
    remote_name: origin
    branch: gh-pages
    local_branch: gh-pages
    when:
      event: push
      branch: master

publish:
  pypi:
    repository: https://pypi.python.org/pypi
    username: c7nbot
    password: $$PYPI_PASS
    distributions:
      - sdist
    when:
      event: tag
      branch: master
      repo: capitalone/cloud-custodian

  docker:
    username: c7nbot
    email: $$HUB_EMAIL
    password: $$HUB_PASS
    repo: capitalone/cloud-custodian
    tag: latest
    when:
      event: push
      branch: master
      repo: capitalone/cloud-custodian

notify:
  gitter:
    webhook: "https://webhooks.gitter.im/e/0bbc88699fe6e59c8993"
    when:
      repo: capitalone/cloud-custodian

# TODO explore caching the whole venv for speed
cache:
  mount:
    - cache
