build:

  unit_tests:
    image: ubuntu:xenial
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
    commands:
      - mkdir -p cache
      - apt-get update && apt-get -y install python-pip
      - pip install -r requirements-dev.txt --cache-dir=cache
      - pip install coveralls --cache-dir=cache
      - python setup.py develop
      - nosetests -s -v tests tools

  pypy_unit_tests:
    # just enough variation to make a matrix not viable
    image: pypy:2
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
    commands:
      - mkdir -p cache
      - pip install -r requirements-dev.txt --cache-dir=cache
      - pip install coveralls --cache-dir=cache
      - pypy setup.py develop
      - nosetests -s -v tests tools/c7n_*
    when:
      event: push
      branch: master


  documentation:
     image: python:2-alpine
     commands:
       - apk update
       - apk add git make
       - git config --global user.email "cibot@cloud-custodian.io"
       - git config --global user.name "Custodian CI"
       - pip install -r requirements-dev.txt --cache-dir=cache
       - make sphinx
       - git remote update origin --prune
       - make ghpages
       - git branch
       # switch back to master post doc-build
       - git checkout master
     when:
       event: push
       branch: master

deploy:
  # sphinx documentation build / per documentation build section
  git_push:
    remote_name: origin
    branch: gh-pages
    local_branch: gh-pages
    when:
      event: push
      branch: master

notify:
  gitter:
    webhook: "https://webhooks.gitter.im/e/0bbc88699fe6e59c8993"
    when:
      repo: capitalone/cloud-custodian

# TODO explore caching the whole venv for speed
cache:
  mount:
    - cache
    - /var/cache/apt/
