AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  AccountIDs:
    Description: "IDs of accounts permitted to register"
    Type: CommaDelimitedList
    Default: "644160558196"
Resources:
  EnrichRegistrations:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: "omnissm-enrich-registrations"
      Runtime: "go1.x"
      CodeUri: "main.zip"
      Handler: "main"
      Tags:
        App: OmniSSM
      Role: arn:aws:iam::644160558196:role/CloudCustodianRole
      Environment:
        Variables:
          OMNISSM_REGISTRATIONS_TABLE: !Ref RegistrationsTable
      Tracing: Active
      Events:
        Periodically:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
  HandleRegistrations:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: "omnissm-handle-registrations"
      Runtime: "go1.x"
      CodeUri: "main.zip"
      Handler: "main"
      Tags:
        App: OmniSSM
      Role: arn:aws:iam::644160558196:role/CloudCustodianRole
      Environment:
        Variables:
          OMNISSM_REGISTRATIONS_TABLE: !Ref RegistrationsTable
          OMNISSM_ACCOUNT_WHITELIST: !Join [ ",", !Ref AccountIDs ]
      Tracing: Active
      Events:
        RegisterInstance:
          Type: Api
          Properties:
            Method: POST
            Path: /register
        RegisterId:
          Type: Api
          Properties:
            Method: PATCH
            Path: /register
  ProcessConfigEvents:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: "omnissm-process-config-events"
      Runtime: "go1.x"
      CodeUri: "main.zip"
      Handler: "main"
      Tags:
        App: OmniSSM
      CodeUri: "."
      Role: arn:aws:iam::644160558196:role/CloudCustodianRole
      Tracing: Active
      Events:
        ConfigFeed:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source: ["aws.config"]
              detail-type: ["Config Configuration Item Change"]
              detail:
                configurationItem:
                  resourceType: ["AWS::EC2::Instance"]
  ProcessDeferredActions:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: "omnissm-process-deferred-actions"
      Runtime: "go1.x"
      CodeUri: "main.zip"
      Handler: "main"
      Tags:
        App: OmniSSM
      Role: arn:aws:iam::644160558196:role/CloudCustodianRole
      Environment:
        Variables:
          OMNISSM_REGISTRATIONS_TABLE: !Ref RegistrationsTable
      Tracing: Active
      Events:
        Periodically:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
  RegistrationsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref TableName
      Tags:
        - Key: App
          Value: OmniSSM
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: ManagedId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ManagedId-index
          KeySchema:
            - AttributeName: ManagedId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  DeferredActionQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: "omnissm-deferred-action-queue"
